// <auto-generated />
using System;
using MangoFaaS.Secrets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MangoFaaS.Secrets.Migrations
{
    [DbContext(typeof(MangoSecretsDbContext))]
    partial class MangoSecretsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MangoFaaS.Secrets.Models.FunctionSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SecretId");

                    b.HasIndex("FunctionId", "SecretId")
                        .IsUnique();

                    b.ToTable("FunctionSecrets");
                });

            modelBuilder.Entity("MangoFaaS.Secrets.Models.Secret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("MangoFaaS.Secrets.Models.FunctionSecret", b =>
                {
                    b.HasOne("MangoFaaS.Secrets.Models.Secret", "Secret")
                        .WithMany("FunctionSecrets")
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secret");
                });

            modelBuilder.Entity("MangoFaaS.Secrets.Models.Secret", b =>
                {
                    b.Navigation("FunctionSecrets");
                });
#pragma warning restore 612, 618
        }
    }
}
