// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>
    /// Balloon device descriptor.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Balloon : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Target balloon size in MiB.</summary>
        public int? AmountMib { get; set; }
        /// <summary>Whether the balloon should deflate when the guest has memory pressure.</summary>
        public bool? DeflateOnOom { get; set; }
        /// <summary>Whether the free page hinting feature is enabled.</summary>
        public bool? FreePageHinting { get; set; }
        /// <summary>Whether the free page reporting feature is enabled.</summary>
        public bool? FreePageReporting { get; set; }
        /// <summary>Interval in seconds between refreshing statistics. A non-zero value will enable the statistics. Defaults to 0.</summary>
        public int? StatsPollingIntervalS { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.Balloon"/> and sets the default values.
        /// </summary>
        public Balloon()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.Balloon"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.Balloon CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.Balloon();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_mib", n => { AmountMib = n.GetIntValue(); } },
                { "deflate_on_oom", n => { DeflateOnOom = n.GetBoolValue(); } },
                { "free_page_hinting", n => { FreePageHinting = n.GetBoolValue(); } },
                { "free_page_reporting", n => { FreePageReporting = n.GetBoolValue(); } },
                { "stats_polling_interval_s", n => { StatsPollingIntervalS = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("amount_mib", AmountMib);
            writer.WriteBoolValue("deflate_on_oom", DeflateOnOom);
            writer.WriteBoolValue("free_page_hinting", FreePageHinting);
            writer.WriteBoolValue("free_page_reporting", FreePageReporting);
            writer.WriteIntValue("stats_polling_interval_s", StatsPollingIntervalS);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
