// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>
    /// The CPU configuration template defines a set of bit maps as modifiers of flags accessed by register to be disabled/enabled for the microvm.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CpuConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A collection of CPUID leaf modifiers (x86_64 only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier>? CpuidModifiers { get; set; }
#nullable restore
#else
        public List<global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier> CpuidModifiers { get; set; }
#endif
        /// <summary>A collection of KVM capabilities to be added or removed (both x86_64 and aarch64)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? KvmCapabilities { get; set; }
#nullable restore
#else
        public List<string> KvmCapabilities { get; set; }
#endif
        /// <summary>A collection of model specific register modifiers (x86_64 only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MangoFaaS.Firecracker.API.Models.MsrModifier>? MsrModifiers { get; set; }
#nullable restore
#else
        public List<global::MangoFaaS.Firecracker.API.Models.MsrModifier> MsrModifiers { get; set; }
#endif
        /// <summary>A collection of register modifiers (aarch64 only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MangoFaaS.Firecracker.API.Models.ArmRegisterModifier>? RegModifiers { get; set; }
#nullable restore
#else
        public List<global::MangoFaaS.Firecracker.API.Models.ArmRegisterModifier> RegModifiers { get; set; }
#endif
        /// <summary>A collection of vCPU features to be modified (aarch64 only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MangoFaaS.Firecracker.API.Models.VcpuFeatures>? VcpuFeatures { get; set; }
#nullable restore
#else
        public List<global::MangoFaaS.Firecracker.API.Models.VcpuFeatures> VcpuFeatures { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.CpuConfig"/> and sets the default values.
        /// </summary>
        public CpuConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.CpuConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.CpuConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.CpuConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpuid_modifiers", n => { CpuidModifiers = n.GetCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier>(global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "kvm_capabilities", n => { KvmCapabilities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "msr_modifiers", n => { MsrModifiers = n.GetCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.MsrModifier>(global::MangoFaaS.Firecracker.API.Models.MsrModifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reg_modifiers", n => { RegModifiers = n.GetCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.ArmRegisterModifier>(global::MangoFaaS.Firecracker.API.Models.ArmRegisterModifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "vcpu_features", n => { VcpuFeatures = n.GetCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.VcpuFeatures>(global::MangoFaaS.Firecracker.API.Models.VcpuFeatures.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier>("cpuid_modifiers", CpuidModifiers);
            writer.WriteCollectionOfPrimitiveValues<string>("kvm_capabilities", KvmCapabilities);
            writer.WriteCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.MsrModifier>("msr_modifiers", MsrModifiers);
            writer.WriteCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.ArmRegisterModifier>("reg_modifiers", RegModifiers);
            writer.WriteCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.VcpuFeatures>("vcpu_features", VcpuFeatures);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
