// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>
    /// Modifier for a CPUID leaf and subleaf (x86_64)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CpuidLeafModifier : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>KVM feature flags for this leaf-subleaf</summary>
        public int? Flags { get; set; }
        /// <summary>CPUID leaf index as hex, binary, or decimal string (e.g., &quot;0x0&quot;, &quot;0b0&quot;, &quot;0&quot;))</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Leaf { get; set; }
#nullable restore
#else
        public string Leaf { get; set; }
#endif
        /// <summary>Register modifiers for this CPUID leaf</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier>? Modifiers { get; set; }
#nullable restore
#else
        public List<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier> Modifiers { get; set; }
#endif
        /// <summary>CPUID subleaf index as hex, binary, or decimal string (e.g., &quot;0x0&quot;, &quot;0b0&quot;, &quot;0&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subleaf { get; set; }
#nullable restore
#else
        public string Subleaf { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier"/> and sets the default values.
        /// </summary>
        public CpuidLeafModifier()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.CpuidLeafModifier();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "flags", n => { Flags = n.GetIntValue(); } },
                { "leaf", n => { Leaf = n.GetStringValue(); } },
                { "modifiers", n => { Modifiers = n.GetCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier>(global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subleaf", n => { Subleaf = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("flags", Flags);
            writer.WriteStringValue("leaf", Leaf);
            writer.WriteCollectionOfObjectValues<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier>("modifiers", Modifiers);
            writer.WriteStringValue("subleaf", Subleaf);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
