// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>Target CPUID register name</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CpuidRegisterModifier_register
    {
        [EnumMember(Value = "eax")]
        #pragma warning disable CS1591
        Eax,
        #pragma warning restore CS1591
        [EnumMember(Value = "ebx")]
        #pragma warning disable CS1591
        Ebx,
        #pragma warning restore CS1591
        [EnumMember(Value = "ecx")]
        #pragma warning disable CS1591
        Ecx,
        #pragma warning restore CS1591
        [EnumMember(Value = "edx")]
        #pragma warning disable CS1591
        Edx,
        #pragma warning restore CS1591
    }
}
