// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>
    /// Modifier for a specific CPUID register within a leaf (x86_64)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CpuidRegisterModifier : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>32-bit bitmap string defining which bits to modify. Format is &quot;0b&quot; followed by 32 characters where &apos;0&apos; = clear bit, &apos;1&apos; = set bit, &apos;x&apos; = don&apos;t modify. Example &quot;0b00000000000000000000000000000001&quot; or &quot;0bxxxxxxxxxxxxxxxxxxxxxxxxxxxx0001&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bitmap { get; set; }
#nullable restore
#else
        public string Bitmap { get; set; }
#endif
        /// <summary>Target CPUID register name</summary>
        public global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier_register? Register { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier"/> and sets the default values.
        /// </summary>
        public CpuidRegisterModifier()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitmap", n => { Bitmap = n.GetStringValue(); } },
                { "register", n => { Register = n.GetEnumValue<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier_register>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bitmap", Bitmap);
            writer.WriteEnumValue<global::MangoFaaS.Firecracker.API.Models.CpuidRegisterModifier_register>("register", Register);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
