// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    /// <summary>
    /// The status of the hotpluggable memory device (virtio-mem)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MemoryHotplugStatus : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>(Logical) Block size for the hotpluggable memory in MiB.</summary>
        public int? BlockSizeMib { get; set; }
        /// <summary>Plugged size for the hotpluggable memory in MiB.</summary>
        public int? PluggedSizeMib { get; set; }
        /// <summary>Requested size for the hotpluggable memory in MiB.</summary>
        public int? RequestedSizeMib { get; set; }
        /// <summary>Slot size for the hotpluggable memory in MiB.</summary>
        public int? SlotSizeMib { get; set; }
        /// <summary>Total size of the hotpluggable memory in MiB.</summary>
        public int? TotalSizeMib { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.MemoryHotplugStatus"/> and sets the default values.
        /// </summary>
        public MemoryHotplugStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.MemoryHotplugStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.MemoryHotplugStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.MemoryHotplugStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "block_size_mib", n => { BlockSizeMib = n.GetIntValue(); } },
                { "plugged_size_mib", n => { PluggedSizeMib = n.GetIntValue(); } },
                { "requested_size_mib", n => { RequestedSizeMib = n.GetIntValue(); } },
                { "slot_size_mib", n => { SlotSizeMib = n.GetIntValue(); } },
                { "total_size_mib", n => { TotalSizeMib = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("block_size_mib", BlockSizeMib);
            writer.WriteIntValue("plugged_size_mib", PluggedSizeMib);
            writer.WriteIntValue("requested_size_mib", RequestedSizeMib);
            writer.WriteIntValue("slot_size_mib", SlotSizeMib);
            writer.WriteIntValue("total_size_mib", TotalSizeMib);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
