// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MangoFaaS.Firecracker.API.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Pmem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identificator for this device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Host level path for the virtio-pmem device to use as a backing file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PathOnHost { get; set; }
#nullable restore
#else
        public string PathOnHost { get; set; }
#endif
        /// <summary>Flag to map backing file in read-only mode.</summary>
        public bool? ReadOnly { get; set; }
        /// <summary>Flag to make this device be the root device for VM boot. Setting this flag will fail if there is another device configured to be a root device already.</summary>
        public bool? RootDevice { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Models.Pmem"/> and sets the default values.
        /// </summary>
        public Pmem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.Pmem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MangoFaaS.Firecracker.API.Models.Pmem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MangoFaaS.Firecracker.API.Models.Pmem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "path_on_host", n => { PathOnHost = n.GetStringValue(); } },
                { "read_only", n => { ReadOnly = n.GetBoolValue(); } },
                { "root_device", n => { RootDevice = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("path_on_host", PathOnHost);
            writer.WriteBoolValue("read_only", ReadOnly);
            writer.WriteBoolValue("root_device", RootDevice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
