// <auto-generated/>
#pragma warning disable CS0618
using MangoFaaS.Firecracker.API.NetworkInterfaces.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MangoFaaS.Firecracker.API.NetworkInterfaces
{
    /// <summary>
    /// Builds and executes requests for operations under \network-interfaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NetworkInterfacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MangoFaaS.Firecracker.API.networkInterfaces.item collection</summary>
        /// <param name="position">The id of the guest network interface</param>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.NetworkInterfaces.Item.WithIface_ItemRequestBuilder"/></returns>
        public global::MangoFaaS.Firecracker.API.NetworkInterfaces.Item.WithIface_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("iface_id", position);
                return new global::MangoFaaS.Firecracker.API.NetworkInterfaces.Item.WithIface_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.NetworkInterfaces.NetworkInterfacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkInterfacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/network-interfaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.NetworkInterfaces.NetworkInterfacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetworkInterfacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/network-interfaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
