// <auto-generated/>
#pragma warning disable CS0618
using MangoFaaS.Firecracker.API.Actions;
using MangoFaaS.Firecracker.API.Balloon;
using MangoFaaS.Firecracker.API.BootSource;
using MangoFaaS.Firecracker.API.CpuConfig;
using MangoFaaS.Firecracker.API.Drives;
using MangoFaaS.Firecracker.API.Entropy;
using MangoFaaS.Firecracker.API.Logger;
using MangoFaaS.Firecracker.API.MachineConfig;
using MangoFaaS.Firecracker.API.Metrics;
using MangoFaaS.Firecracker.API.Mmds;
using MangoFaaS.Firecracker.API.Models;
using MangoFaaS.Firecracker.API.NetworkInterfaces;
using MangoFaaS.Firecracker.API.Serial;
using MangoFaaS.Firecracker.API.Snapshot;
using MangoFaaS.Firecracker.API.VersionNamespace;
using MangoFaaS.Firecracker.API.Vm;
using MangoFaaS.Firecracker.API.Vsock;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MangoFaaS.Firecracker.API
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FirecrackerClient : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::MangoFaaS.Firecracker.API.Actions.ActionsRequestBuilder Actions
        {
            get => new global::MangoFaaS.Firecracker.API.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The balloon property</summary>
        public global::MangoFaaS.Firecracker.API.Balloon.BalloonRequestBuilder Balloon
        {
            get => new global::MangoFaaS.Firecracker.API.Balloon.BalloonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bootSource property</summary>
        public global::MangoFaaS.Firecracker.API.BootSource.BootSourceRequestBuilder BootSource
        {
            get => new global::MangoFaaS.Firecracker.API.BootSource.BootSourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cpuConfig property</summary>
        public global::MangoFaaS.Firecracker.API.CpuConfig.CpuConfigRequestBuilder CpuConfig
        {
            get => new global::MangoFaaS.Firecracker.API.CpuConfig.CpuConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The drives property</summary>
        public global::MangoFaaS.Firecracker.API.Drives.DrivesRequestBuilder Drives
        {
            get => new global::MangoFaaS.Firecracker.API.Drives.DrivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entropy property</summary>
        public global::MangoFaaS.Firecracker.API.Entropy.EntropyRequestBuilder Entropy
        {
            get => new global::MangoFaaS.Firecracker.API.Entropy.EntropyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logger property</summary>
        public global::MangoFaaS.Firecracker.API.Logger.LoggerRequestBuilder Logger
        {
            get => new global::MangoFaaS.Firecracker.API.Logger.LoggerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The machineConfig property</summary>
        public global::MangoFaaS.Firecracker.API.MachineConfig.MachineConfigRequestBuilder MachineConfig
        {
            get => new global::MangoFaaS.Firecracker.API.MachineConfig.MachineConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::MangoFaaS.Firecracker.API.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::MangoFaaS.Firecracker.API.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mmds property</summary>
        public global::MangoFaaS.Firecracker.API.Mmds.MmdsRequestBuilder Mmds
        {
            get => new global::MangoFaaS.Firecracker.API.Mmds.MmdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The networkInterfaces property</summary>
        public global::MangoFaaS.Firecracker.API.NetworkInterfaces.NetworkInterfacesRequestBuilder NetworkInterfaces
        {
            get => new global::MangoFaaS.Firecracker.API.NetworkInterfaces.NetworkInterfacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serial property</summary>
        public global::MangoFaaS.Firecracker.API.Serial.SerialRequestBuilder Serial
        {
            get => new global::MangoFaaS.Firecracker.API.Serial.SerialRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The snapshot property</summary>
        public global::MangoFaaS.Firecracker.API.Snapshot.SnapshotRequestBuilder Snapshot
        {
            get => new global::MangoFaaS.Firecracker.API.Snapshot.SnapshotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The version property</summary>
        public global::MangoFaaS.Firecracker.API.VersionNamespace.VersionRequestBuilder Version
        {
            get => new global::MangoFaaS.Firecracker.API.VersionNamespace.VersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vm property</summary>
        public global::MangoFaaS.Firecracker.API.Vm.VmRequestBuilder Vm
        {
            get => new global::MangoFaaS.Firecracker.API.Vm.VmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vsock property</summary>
        public global::MangoFaaS.Firecracker.API.Vsock.VsockRequestBuilder Vsock
        {
            get => new global::MangoFaaS.Firecracker.API.Vsock.VsockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.FirecrackerClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FirecrackerClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "http://localhost";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// Returns general information about an instance.
        /// </summary>
        /// <returns>A <see cref="global::MangoFaaS.Firecracker.API.Models.InstanceInfo"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MangoFaaS.Firecracker.API.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MangoFaaS.Firecracker.API.Models.InstanceInfo?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MangoFaaS.Firecracker.API.Models.InstanceInfo> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::MangoFaaS.Firecracker.API.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MangoFaaS.Firecracker.API.Models.InstanceInfo>(requestInfo, global::MangoFaaS.Firecracker.API.Models.InstanceInfo.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns general information about an instance.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FirecrackerClientGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
