// <auto-generated/>
#pragma warning disable CS0618
using MangoFaaS.Firecracker.API.Hotplug.Memory;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MangoFaaS.Firecracker.API.Hotplug
{
    /// <summary>
    /// Builds and executes requests for operations under \hotplug
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HotplugRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The memory property</summary>
        public global::MangoFaaS.Firecracker.API.Hotplug.Memory.MemoryRequestBuilder Memory
        {
            get => new global::MangoFaaS.Firecracker.API.Hotplug.Memory.MemoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Hotplug.HotplugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HotplugRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hotplug", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Hotplug.HotplugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HotplugRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hotplug", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
