// <auto-generated/>
#pragma warning disable CS0618
using MangoFaaS.Firecracker.API.Balloon.Hinting.Start;
using MangoFaaS.Firecracker.API.Balloon.Hinting.Status;
using MangoFaaS.Firecracker.API.Balloon.Hinting.Stop;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MangoFaaS.Firecracker.API.Balloon.Hinting
{
    /// <summary>
    /// Builds and executes requests for operations under \balloon\hinting
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HintingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The start property</summary>
        public global::MangoFaaS.Firecracker.API.Balloon.Hinting.Start.StartRequestBuilder Start
        {
            get => new global::MangoFaaS.Firecracker.API.Balloon.Hinting.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::MangoFaaS.Firecracker.API.Balloon.Hinting.Status.StatusRequestBuilder Status
        {
            get => new global::MangoFaaS.Firecracker.API.Balloon.Hinting.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::MangoFaaS.Firecracker.API.Balloon.Hinting.Stop.StopRequestBuilder Stop
        {
            get => new global::MangoFaaS.Firecracker.API.Balloon.Hinting.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Balloon.Hinting.HintingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HintingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/balloon/hinting", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MangoFaaS.Firecracker.API.Balloon.Hinting.HintingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HintingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/balloon/hinting", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
